/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiPlaceImageRouteImport } from './routes/api/place-image'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAirQualityRouteImport } from './routes/api/air-quality'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlaceImageRoute = ApiPlaceImageRouteImport.update({
  id: '/api/place-image',
  path: '/api/place-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAirQualityRoute = ApiAirQualityRouteImport.update({
  id: '/api/air-quality',
  path: '/api/air-quality',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/air-quality': typeof ApiAirQualityRoute
  '/api/chat': typeof ApiChatRoute
  '/api/place-image': typeof ApiPlaceImageRoute
  '/api/tts': typeof ApiTtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/air-quality': typeof ApiAirQualityRoute
  '/api/chat': typeof ApiChatRoute
  '/api/place-image': typeof ApiPlaceImageRoute
  '/api/tts': typeof ApiTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/air-quality': typeof ApiAirQualityRoute
  '/api/chat': typeof ApiChatRoute
  '/api/place-image': typeof ApiPlaceImageRoute
  '/api/tts': typeof ApiTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/air-quality' | '/api/chat' | '/api/place-image' | '/api/tts'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/air-quality' | '/api/chat' | '/api/place-image' | '/api/tts'
  id:
    | '__root__'
    | '/'
    | '/api/air-quality'
    | '/api/chat'
    | '/api/place-image'
    | '/api/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAirQualityRoute: typeof ApiAirQualityRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPlaceImageRoute: typeof ApiPlaceImageRoute
  ApiTtsRoute: typeof ApiTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/place-image': {
      id: '/api/place-image'
      path: '/api/place-image'
      fullPath: '/api/place-image'
      preLoaderRoute: typeof ApiPlaceImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/air-quality': {
      id: '/api/air-quality'
      path: '/api/air-quality'
      fullPath: '/api/air-quality'
      preLoaderRoute: typeof ApiAirQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAirQualityRoute: ApiAirQualityRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPlaceImageRoute: ApiPlaceImageRoute,
  ApiTtsRoute: ApiTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
